ADSProductAPIs=\product_package\conf\adsf\ADSProductAPIs.xml
SecurityApiV2=\web\adsm\WEB-INF\security\security-api-v2.xml
WebHeader=\resources\tomcat\web_header.xml
WebFooter=\resources\tomcat\web_footer.xml
ServletAPI=\product_package\conf\adsm\servlet-api.xml
ADMPAPIDetails=\product_package\conf\adsm\ADMPAPIDetails.xml
StrutsConfig=\web\adsm\WEB-INF\struts-config.xml
TaskFlow=\product_package\conf\adsm\taskflow.xml
ADSPatchUpdateManager=\product_package\conf\adsf\ADSPatchUpdateManager.xml
DelayedTaskCategory=\product_package\conf\adsm\DelayedTaskCategory.xml
ReportXML=\product_package\conf\adsm\Reports.xml
TableXmlDir=\product_package\conf\adsm
